apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169710461
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169710461
    app.kubernetes.io/part-of: test-app-169710461
  name: java-quarkus-169710461
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169710461
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169710461
    spec:
      containers:
      - image: quay.io/hacdev/frdob7l4-tenant/test-app-169710461/java-quarkus-169710461@sha256:fde86e2bf4c4bbc0f838c88456906bef7a6da25695a7536626fc8969bd7f1f54
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
